package com.guberan.logfaqai.model;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDateTime;

@Entity
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Getter
@Setter
public class Question {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String text;

    @Column(columnDefinition = "TEXT")
    private String answer;

    private boolean validated;

    private boolean autoGenerated;

    private LocalDateTime askedAt;
    
    public Question(String text, String answer, boolean validated, boolean autoGenerated) {
        this.text = text;
        this.answer = answer;
        this.validated = validated;
        this.autoGenerated = autoGenerated;
        this.askedAt = LocalDateTime.now();
    }
}