package com.guberan.logfaqai.service;

import com.guberan.logfaqai.dto.AskResponse;
import com.guberan.logfaqai.model.Question;
import com.guberan.logfaqai.repository.QuestionRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;


@Service
@RequiredArgsConstructor
public class FaqService {

    private final OpenAiService openAiService;
    private final QuestionRepository questionRepository;

    public AskResponse processQuestion(String questionText) {
        String answer = openAiService.generateAnswer(questionText);

        Question q = new Question();
        q.setText(questionText);
        q.setAnswer(answer);
        q.setValidated(false);
        q.setAutoGenerated(true);
        q.setAskedAt(LocalDateTime.now());

        questionRepository.save(q);

        AskResponse response = new AskResponse();
        response.setQuestion(questionText);
        response.setAnswer(answer);
        response.setValidated(false);

        return response;
    }
}