package com.guberan.logfaqai.controller;

import com.guberan.logfaqai.dto.ValidationRequest;
import com.guberan.logfaqai.model.Question;
import com.guberan.logfaqai.repository.QuestionRepository;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import lombok.RequiredArgsConstructor;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@RestController
@RequestMapping("/api/admin/questions")
@RequiredArgsConstructor
//@PreAuthorize("hasAuthority('SCOPE_admin')")
public class AdminController {

    private final QuestionRepository questionRepository;

    @GetMapping
    @PreAuthorize("hasAnyRole('ADMIN','RAG_BUILDER')")
    public List<Question> getQuestions(@RequestParam(required = false) Boolean validated) {
        if (validated == null) {
            return questionRepository.findAll();
        } else {
            return questionRepository.findByValidated(validated);
        }
    }

    @PostMapping("/{id}/validate")
    @PreAuthorize("hasRole('ADMIN')")
    @Operation(
            summary = "Validate or correct a generated answer",
            requestBody = @io.swagger.v3.oas.annotations.parameters.RequestBody(
                    required = true,
                    content = @Content(
                            mediaType = "application/json",
                            examples = {
                                    @ExampleObject(
                                            name = "Manual correction",
                                            summary = "Validate with a corrected answer",
                                            value = """
                                                        {
                                                          "correctedAnswer": "Kafka processes real-time logs and sends them to Elasticsearch."
                                                        }
                                                    """
                                    )
                            }
                    )
            )
    )
    public ResponseEntity<String> validateResponse(@PathVariable Long id, @RequestBody ValidationRequest request) {
        return questionRepository.findById(id)
                .map(question -> {
                    question.setAnswer(request.getCorrectedAnswer());
                    question.setValidated(true);
                    question.setAutoGenerated(false);
                    questionRepository.save(question);
                    return ResponseEntity.ok("Question validated.");
                })
                .orElseGet(() -> ResponseEntity.notFound().build());
    }
}